Add connection tests
pia-foss/mobile-android-legacy pull request #42
Opened 2023-10-19 03:33 UTC by kp-ruth-o

## Purpose
Created a protocol connection tests for both OpenVPN and Wireguard and also quick connect from the main screen/dashboard.

The base will change to master once PIA-634 has been merged. Doing this for early pr review 🙏.

2023-10-23 10:44 UTC, kp-aldo-pedromingo reviewed
I've added just one minor readability improvement. Overall looks great. Well done!

2023-10-23 10:44 UTC, kp-aldo-pedromingo commented on app/src/androidTest/java/tests/ProtocolConnectivityTests.kt
> +    fun openVPNConnectivity() {
Super readable! 🍬 !

2023-10-23 10:44 UTC, kp-aldo-pedromingo commented on app/src/androidTest/java/screens/steps/MainScreenStepObjects.kt
> +    fun clickOnQuickConnect(uiObject : UiObject) {
`clickOnQuickConnect` assumes that you are calling it with the right parameters - namely a quick connect UI object. This is problematic because:
1) The name of the function does not suggest that you have to have to call it with an `UiObject` as a parameter
2) This function can be used to click any UI object. Even those that are not Quick Connect objects

My suggestions are:

- Remove this function and, in `QuickConnectTests.kt` call the click functions directly: mainScreenPageObjects.quickConnectFlag1.click() and `mainScreenPageObjects.quickConnectText2.click()`
- Create 2 separate functions as `clickConnect()` that accept no parameters: `clickQuickConnectFlag1()` and `clickQuickConnectText2()`

2023-10-24 03:54 UTC, kp-ruth-o commented on app/src/androidTest/java/screens/steps/MainScreenStepObjects.kt
> +    fun clickOnQuickConnect(uiObject : UiObject) {
Good catch! 

I'll go for the first one in the mean time!

2023-10-24 07:04 UTC, kp-andrei-madescu commented on app/src/androidTest/java/screens/steps/MainScreenStepObjects.kt
> +    fun clickOnQuickConnect(uiObject : UiObject) {
I agree with Aldo. Do not see that great of a value in this method and it would be easier to read if you would call this directly in the tests.

However, I do not think that a `clickConnect()` method would be that useful either. At least not at this point, and you might want to keep it in mind for when these tests will be extended.

2023-10-24 07:04 UTC, kp-andrei-madescu commented on app/src/androidTest/java/screens/objects/MainScreenPageObjects.kt
I am curious about the reasoning behind choosing `quick_server_flag_1` and `quick_server_name_2`, instead of going with either 2 flag entries or 2 name entries. 

When scaling the tests and making sure that we can connect to all 'Quick Connect' servers, all server IDs will be useful. 

However, at this point, if you just want to make sure you can connect by both clicking the flag and the text, I would suggest going with: `quick_server_flag_1` and `quick_server_name_1`.

2023-10-24 07:57 UTC, kp-ruth-o commented on app/src/androidTest/java/screens/objects/MainScreenPageObjects.kt
good catch on this one!  resolved this and test only the first flag for this coverage!

2023-10-25 06:48 UTC, kp-aldo-pedromingo reviewed
Just a very minor remark. Nice job! Super clean and readable.

2023-10-25 06:48 UTC, kp-aldo-pedromingo commented on app/src/androidTest/java/tests/QuickConnectTests.kt
> +    fun validateQuickConnectConnectionWhenFlagIsClick()
Should it be validateQuickConnectConnectionWhenFlagIsClick**ed**?
same for validateQuickConnectConnectionWhenTextIsClick**ed**

2023-10-25 06:55 UTC, kp-andrei-madescu requested changes

2023-10-25 06:55 UTC, kp-andrei-madescu commented on app/src/androidTest/java/tests/QuickConnectTests.kt
> +        mainScreenStepObjects.clickConnect()
Do we still need this step if we are already clicking on the Quick Connect element?

2023-10-25 06:55 UTC, kp-andrei-madescu commented on app/src/androidTest/java/tests/QuickConnectTests.kt
> +        mainScreenStepObjects.clickConnect()
Same as above.

2023-10-25 06:55 UTC, kp-andrei-madescu commented on app/src/androidTest/java/tests/QuickConnectTests.kt
> +    fun validateQuickConnectConnectionWhenFlagIsClick()
I would suggest `validateQuickConnectConectivityWhenFlagIsClicked` to be more explicit and follow somehow the names from the protocol tests.

2023-10-25 06:55 UTC, kp-andrei-madescu commented on app/src/androidTest/java/tests/QuickConnectTests.kt
> +    fun validateQuickConnectConnectionWhenTextIsClick()
I would suggest `validateQuickConnectConectivityWhenTextIsClicked` to be more explicit and follow somehow the names from the protocol tests.

2023-10-25 07:07 UTC, kp-ruth-o commented on app/src/androidTest/java/tests/QuickConnectTests.kt
> +    fun validateQuickConnectConnectionWhenFlagIsClick()
I feel like the name of the tests is actually too long, so i'll remove the word validate and instead use `quickConnectConnectionWhenFlagIsClicked` and `quickConnectConnectionWhenTextIsClicked`

2023-10-25 07:08 UTC, kp-ruth-o commented on app/src/androidTest/java/tests/QuickConnectTests.kt
> +        mainScreenStepObjects.clickConnect()
good catch! amending it!

2023-10-25 07:08 UTC, kp-ruth-o commented on app/src/androidTest/java/tests/QuickConnectTests.kt
> +        mainScreenStepObjects.clickConnect()
amending it! thank you!

2023-10-25 07:09 UTC, kp-ruth-o commented on app/src/androidTest/java/tests/QuickConnectTests.kt
> +    fun validateQuickConnectConnectionWhenTextIsClick()
ahhh i love the word connectivity! let me use it!  thank you!

2023-10-25 07:13 UTC, kp-ruth-ondrada commented on app/src/androidTest/java/tests/QuickConnectTests.kt
> +    fun validateQuickConnectConnectionWhenFlagIsClick()
ahhh i love the word connectivity! will amend!

2023-10-25 07:20 UTC, kp-andrei-madescu approved these changes

2023-10-25 07:22 UTC, kp-andrei-madescu commented
Approved the changes you've made.

Clean and easy-to-read tests. Great work, Ruth! 🚀

2023-10-25 07:50 UTC, merged